### ISSUE TITLE
Provide information how to use the program

### ISSUE THREAD

**Issue by Kaligule** [rocky/pygtk3-pstree#1]
I couldn't run it.
- running `make` doesn't do anyrhing for me
-  running `make install` and `make verbose-install` needs some setup.py which doesn't exist.
- runing main.py produces an empty window.

**Comment by rocky** [comment]
First and foremost this isn't a finished project or one that I currently working on. The last commit I made on this was July of last year! 

I currently am not using python much these days. 

That said I just tried runnning `main.py` and I get the below screenshot:

![screenshot from 2016-03-09 04 50 59](https://cloud.githubusercontent.com/assets/8851/13631485/f0065c6e-e5b2-11e5-8d70-25fd300ee256.png)

**Comment by Kaligule** [comment]
So running `main.py` works for you, but not for me. Thanks, I will try to figure this out.

**Comment by rocky** [comment]
@Kaligule That's the spirit! 

If you do get this working and finish the project please let me know. The idea is cool and I would like to have an updated version of xps, it's just a lot more work that I can handle in the foreseeable future.
